version: '3.9'
services:
  backend:
    build: ./backend
    environment:
      - ELASTICSEARCH=http://host.docker.internal:9200
      - DATA=/app/data
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
  frontend:
    build: ./frontend
    environment:
      - BACKEND_URL=http://backend:5000/
      - DATA=/app/data
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data