version: '3.9'
services:
  backend:
    build: ./backend
    environment:
      - ELASTICSEARCH=http://host.docker.internal:9200
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    environment:
      - BACKEND_URL=http://backend:5000/
    ports:
      - "5001:5001"